name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - release-*

jobs:
  build:
    name: Build Plugin
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_artifactory_user: '${{secrets.ARTIFACTORY_USER}}'
      ORG_GRADLE_PROJECT_artifactory_password: '${{secrets.ARTIFACTORY_TOKEN}}'
    steps:
      - name: Fix up git URLs
        run: echo -e '[url "https://github.com/"]\n  insteadOf = "git://github.com/"' >> ~/.gitconfig

      - name: checkout code
        uses: actions/checkout@v2

      - name: fetch full history
        run: git fetch --prune --tags --unshallow

      - name: setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: run tests
        run: ./gradlew test --info

      - name: build
        run: |
          ./gradlew releaseBundle
          ls -l ./build/distributions

      - name: archive build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: build/distributions
