name: Create Github Release

on:
  push:
    branches:
      - master

jobs:
  create-release:
    name: Create Github Release
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.ARMORY_PLATFORM_GITHUB_PAT_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Fetch full history
        run: git fetch --prune --tags --unshallow
        shell: bash

      - name: Bump version and push tag
        id: push_tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.ARMORY_PLATFORM_GITHUB_PAT_TOKEN }}
          default_bump: patch
          release_branches: master

      - name: Fetch Refresh
        run: git fetch --prune --tags
        shell: bash

      - name: Generate Changelog
        id: changelog
        env:
          NEW_TAG: ${{ steps.push_tag.outputs.new_tag }}
          PREVIOUS_TAG: ${{ steps.push_tag.outputs.previous_tag }}
        run: |
          set mode -x
          export CHANGELOG=`git log $NEW_TAG...$PREVIOUS_TAG --oneline`
          echo "CHANGELOG=$CHANGELOG"
          CHANGELOG="${CHANGELOG//$'%'/%25}"
          CHANGELOG="${CHANGELOG//$'\n'/%0A}"
          CHANGELOG="${CHANGELOG//$'\r'/%0D}"
          echo ::set-output name=CHANGELOG::$(echo -e "${CHANGELOG}")
        shell: bash

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ARMORY_PLATFORM_GITHUB_PAT_TOKEN }}
        with:
          tag_name: ${{ steps.push_tag.outputs.new_tag }}
          release_name: ${{ github.event.repository.name }} ${{ steps.push_tag.outputs.new_tag }}
          body: |
            ${{ steps.changelog.outputs.CHANGELOG }}
          draft: false
          prerelease: false
