name: Pull Request Analysis

on:
  pull_request:
    branches:
      - 'main'

jobs:
  pr-analysis:
    name: Build Project
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: build project
        run: ./gradlew build
